title: Slime

description: >
  An Elixir library for rendering Slim-like templates.

baseurl: ""
url: "http://slime-lang.com"
markdown: kramdown
permalink: pretty

github_username: slime-lang


sections:
  - attributes
  - code
  - comments
  - conditionals
  - doctype
  - iteration


exclude:
  - Gemfile
  - Gemfile.lock
  - mix.exs
  - mix.lock
  - CNAME
  - README.md
  - deps
  - _build
